### ISSUE TITLE
[US] :  Report hors forfait mois suivant

### ISSUE THREAD

**Issue by Lurius-Kitsune** [Lurius-Kitsune/AP1-GSB#16]
## Description de l'US
L'utilisateur demande la suppression des lignes de frais hors forfait non valide.
### Contrainte
 - Aucune
### Critère de validation
 - Le système ajoute la ligne hors forfait dans la fiche du mois suivant et la supprime de la fiche courante. Si la fiche du mois suivant n'existe pas, le système génère une nouvelle fiche pour le visiteur en cours de traitement et pour le mois suivant. Cette nouvelle fiche a des valeurs à 0 pour les frais forfaitisés et est dans l'état "Saisie en cours".

**Comment by M3rwin** [comment]
PR effectué
