### ISSUE TITLE
[US] :  Affichage maximum du nombre de fiches

### ISSUE THREAD

**Issue by Lurius-Kitsune** [Lurius-Kitsune/AP1-GSB#55]
## Description de l'US
L'utilisitateur souhaite voir les fiches qui sont validé mais non-rembousser.
### Contrainte
- #44 
### Critère de validation
- Affichage des fiches dans un tableau 
- L'utilisatuer peut afficher jusqu'as 20, 50, 100, 150, 200 fiches.
- L'utilisateur doit pouvoir voir toute les fiches en attente de paiement.

**Comment by M3rwin** [comment]
effectué sur la branche US/45*

**Comment by M3rwin** [comment]
En raison du nombres de problèmes que soulève la fonctionnalité du nombres de visiteurs affiché (par 10, 20, 30, 50), on abandonne cette feature pour rester sur un affichage de 30 visiteurs et la possibilité de naviguer dans les pages de visiteurs.

Ex de problème rencontré : 
Un comptable utilisant l'affichage par 50 et étant sur la dernière page de visiteurs affiché décide passer en affichage par 30. La gestion des visiteurs à afficher et de la page spécifique à afficher est trop complexe.
